using GPT_Lib.Enums;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GPT_Lib.Models;

public class Response
{
  /// <summary>
  /// Id of the organization the API key belongs to.
  /// </summary>
  [JsonProperty("id")]
  public string Id { get; private set; }

  /// <summary>
  /// The type of action requested.
  /// </summary>
  [JsonProperty("object")]
  public string Type { get; private set; }

  /// <summary>
  /// The creation date of the request, in unix seconds.
  /// </summary>
  [JsonProperty("created")]
  public long CreatedAt { get; private set; }

  /// <summary>
  /// The model used to generate the response.
  /// </summary>
  [JsonProperty("model")]
  [JsonConverter(typeof(StringEnumConverter))]
  public Model Model { get; private set; }

  /// <summary>
  /// Info about the tokens used for the prompt and completion.
  /// </summary>
  [JsonProperty("usage")]
  public TokenUsage TokenUsage { get; private set; }

  /// <summary>
  /// The choices generated by the model.
  /// </summary>
  [JsonProperty("choices")]
  public Choice[] Choices { get; private set; }

  public Response(string id, string type, long createdAt, Model model, TokenUsage tokenUsage, Choice[] choices)
  {
    Id = id;
    Type = type;
    CreatedAt = createdAt;
    Model = model;
    TokenUsage = tokenUsage;
    Choices = choices;
  }
}
